steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hello-app:latest'
      - '.'
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hello-app:latest'
  - name: gcr.io/$PROJECT_ID/cloudbuild-attestor
    id: 'Check Vulnerability Scan results'
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
         /scripts/check_vulnerabilities.sh -p $PROJECT_ID -i gcr.io/$PROJECT_ID/hello-app:latest -t 5
tags: ['cloud-builders-community']